[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psz"
version = "1.0.9beta"
description = "Encrypted project archive format (.psz + .psz-data.lor) with multi-language unpackers"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "DarkFox / SlabyLol"}]
keywords = ["archive", "encryption", "aes", "psz", "secure-archive"]
dependencies = [
    "cryptography>=42.0.0",
]

[project.scripts]
psz = "psz.cli:main"

[project.urls]
Homepage = "https://github.com/SlabyLol/psz"
Repository = "https://github.com/SlabyLol/psz"

[tool.setuptools.packages.find]
where = ["."]
include = ["psz*"]
