"""Unpacker generator."""
from pathlib import Path

def _generate_js_lor(key_hex: str, archive_name: str) -> str:
    """Generate a self-contained Node.js unpacker script."""
    stem = Path(archive_name).stem
    lines = [
        "#!/usr/bin/env node",
        "/**",
        f" * PSZ Unpacker (Node.js) - generated for: {archive_name}",
        " *",
        f" *   node {stem}.psz-data.js {archive_name} -o extracted/",
        " *",
        " * Requires Node.js 16+ (built-in crypto).",
        " */",
        '"use strict";',
        "",
        'const fs = require("fs");',
        'const path = require("path");',
        'const crypto = require("crypto");',
        "",
        f'const KEY_HEX = "{key_hex}";',
        'const MAGIC = Buffer.from("PSZ1");',
        "const NONCE_SIZE = 12;",
        "const TAG_SIZE = 16;",
        "",
        "function usage() {",
        '  console.error("Usage: node " + path.basename(__filename) + " <archive.psz> [-o output_dir]");',
        "  process.exit(1);",
        "}",
        "",
        "function extractTar(buf, dest) {",
        "  fs.mkdirSync(dest, { recursive: true });",
        "  let offset = 0;",
        "  while (offset + 512 <= buf.length) {",
        "    const header = buf.subarray(offset, offset + 512);",
        "    offset += 512;",
        "    if (header.every((b) => b === 0)) break;",
        '    const name = header.subarray(0, 100).toString("utf8").replace(/\\0.*$/, "");',
        '    const sizeOct = header.subarray(124, 136).toString("utf8").replace(/\\0| /g, "");',
        "    const type = String.fromCharCode(header[156] || 48);",
        '    const size = parseInt(sizeOct || "0", 8) || 0;',
        '    if (!name || name.includes("..") || name.startsWith("/")) {',
        "      offset += Math.ceil(size / 512) * 512;",
        "      continue;",
        "    }",
        "    const target = path.join(dest, name);",
        '    if (type === "5" || name.endsWith("/")) {',
        "      fs.mkdirSync(target, { recursive: true });",
        "    } else {",
        "      fs.mkdirSync(path.dirname(target), { recursive: true });",
        "      fs.writeFileSync(target, buf.subarray(offset, offset + size));",
        "    }",
        "    offset += Math.ceil(size / 512) * 512;",
        "  }",
        "}",
        "",
        "function main() {",
        "  const args = process.argv.slice(2);",
        "  let archive = null;",
        '  let out = "extracted";',
        "  for (let i = 0; i < args.length; i++) {",
        '    if ((args[i] === "-o" || args[i] === "--output") && args[i + 1]) {',
        "      out = args[++i];",
        '    } else if (!archive && !args[i].startsWith("-")) {',
        "      archive = args[i];",
        "    }",
        "  }",
        "  if (!archive) usage();",
        "",
        "  const data = fs.readFileSync(archive);",
        "  if (!data.subarray(0, 4).equals(MAGIC)) {",
        '    console.error("Error: not a valid PSZ archive");',
        "    process.exit(1);",
        "  }",
        "  const nonce = data.subarray(5, 5 + NONCE_SIZE);",
        "  const ctWithTag = data.subarray(5 + NONCE_SIZE);",
        "  if (ctWithTag.length < TAG_SIZE) {",
        '    console.error("Error: ciphertext too short");',
        "    process.exit(1);",
        "  }",
        "  const tag = ctWithTag.subarray(ctWithTag.length - TAG_SIZE);",
        "  const ct = ctWithTag.subarray(0, ctWithTag.length - TAG_SIZE);",
        '  const key = Buffer.from(KEY_HEX, "hex");',
        "",
        "  let plain;",
        "  try {",
        '    const decipher = crypto.createDecipheriv("aes-256-gcm", key, nonce);',
        "    decipher.setAuthTag(tag);",
        "    plain = Buffer.concat([decipher.update(ct), decipher.final()]);",
        "  } catch (e) {",
        '    console.error("Error: decryption failed");',
        "    process.exit(1);",
        "  }",
        "",
        "  extractTar(plain, out);",
        '  console.log("Successfully extracted to: " + path.resolve(out));',
        "}",
        "",
        "main();",
        "",
    ]
    return "\n".join(lines)
